apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mma.fullname" . }}-config
  labels:
    {{- include "mma.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
